(in-package :vm1)

(defparameter +factorial-asm+
  #((const n 5)
    (call factorial n)
    (get-ret result 0)
    (print result)
    (halt)
    (label factorial)
    (get-arg n 0)
    (const acc 1)
    (label loop)
    (jz done n)
    (mul acc acc n)
    (sub n n 1)
    (jmp loop)
    (label done)
    (ret acc)))

(defparameter +fibonacci-asm+
  #((const n 6)
    (call fibonacci n)
    (get-ret result 0)
    (print result)
    (halt)
    (label fibonacci)
    (get-arg n 0)
    (const a 0)
    (const b 1)
    (label loop)
    (jz done n)
    (add tmp a b)
    (mov a b)
    (mov b tmp)
    (sub n n 1)
    (jmp loop)
    (label done)
    (ret a)))
