(in-package :vm1)

(defparameter +factorial-asm+
  #((scope-enter)
    (const n 5)
    (call factorial n)
    (get-ret result 0)
    (print result)
    (halt)
    (label factorial)
    (scope-enter)
    (get-arg n 0)
    (const acc 1)
    (label loop)
    (jz done n)
    (mul acc acc n)
    (sub n n 1)
    (jmp loop)
    (label done)
    (ret acc)))
